eShopSolution.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopSolution.AdminApp/Controllers/ProductController.cs
using System.Linq;
using System.Threading.Tasks;
using eShopSolution.AdminApp.ApiIntegration.Interface;
using eShopSolution.Data.Entities;
using eShopSolution.Utilities.Constants;
using eShopSolution.ViewModels.Catalog.Categories;
using eShopSolution.ViewModels.Catalog.Products;
using eShopSolution.ViewModels.Common;
using eShopSolution.ViewModels.System.Products;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace eShopSolution.AdminApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;

        private readonly ICategoryApiClient _categoryApiClient;

        public ProductController(IProductApiClient productApiClient,
            IConfiguration configuration,
            ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IActionResult> Index(string keyword, int? categoryId, int pageIndex = 1, int pageSize = 10)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId,
                CategoryId = categoryId
            };
            var data = await _productApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;

            var categories = await _categoryApiClient.GetAll(languageId);

            List<CategoryVm> cateDistince = new List<CategoryVm>();
            foreach (var item in categories)
            {
                if (item.Name != "N/A")
                {
                  
                    cateDistince.Add(item);
                }
            }

          
            ViewBag.Categories = cateDistince.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId.Value == x.Id
            });

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.CreateProduct(request);
            if (result)
            {
                TempData["result"] = "Thêm mới sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> CategoryAssign(int id)
        {
            var roleAssignRequest = await GetCategoryAssignRequest(id);
            return View(roleAssignRequest);
        }

        //ham save danh muc
        [HttpPost]
        public async Task<IActionResult> CategoryAssign(CategoryAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.CategoryAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetCategoryAssignRequest(request.Id);

            return View(roleAssignRequest);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var product = await _productApiClient.GetById(id, languageId);
            var editVm = new ProductUpdateRequest()
            {
                Id = product.Id,
                Description = product.Description,
                Details = product.Details,
                Name = product.Name,
                SeoAlias = product.SeoAlias,
                SeoDescription = product.SeoDescription,
                SeoTitle = product.SeoTitle
            };
            return View(editVm);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] ProductUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _productApiClient.UpdateProduct(request);
            if (result)
            {
                TempData["result"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật sản phẩm thất bại");
            return View(request);
        }

        private async Task<CategoryAssignRequest> GetCategoryAssignRequest(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var productObj = await _productApiClient.GetById(id, languageId);
            var categories = await _categoryApiClient.GetAll(languageId);
            var categoryAssignRequest = new CategoryAssignRequest();
            foreach (var role in categories)
            {
                categoryAssignRequest.Categories.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = productObj.Categories.Contains(role.Name)
                });
            }
            return categoryAssignRequest;
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new ProductDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.DeleteProduct(request.Id);
            if (result)
            {
                TempData["result"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return View(request);
        }
    }
}

eShopSolution.AdminApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using eShopSolution.AdminApp.ApiIntegration.Interface;
using eShopSolution.ViewModels.Common;
using eShopSolution.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;

namespace eShopSolution.AdminApp.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiClient _roleApiClient;

        public UserController(IUserApiClient userApiClient,
            IRoleApiClient roleApiClient,
            IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
            _roleApiClient = roleApiClient;
        }

        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userApiClient.GetUsersPagings(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.RegisterUser(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm mới người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserUpdateRequest()
                {
                    Dob = user.Dob,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    Id = id
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.UpdateUser(request.Id, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new UserDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.Delete(request.Id);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequest = await GetRoleAssignRequest(id);
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.RoleAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật quyền thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetRoleAssignRequest(request.Id);

            return View(roleAssignRequest);
        }

        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var userObj = await _userApiClient.GetById(id);
            var roleObj = await _roleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            foreach (var role in roleObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.ResultObj.Roles.Contains(role.Name)
                });
            }
            return roleAssignRequest;
        }
    }
}

eShopSolution.AdminApp/Views/Product/CategoryAssign.cshtml
@model eShopSolution.ViewModels.Catalog.Products.CategoryAssignRequest

@{
    ViewData["Title"] = "Gán danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Gán quyền</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Gán danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="CategoryAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @for (var i = 0; i < Model.Categories.Count; i++)
                {
                   @* @if (Model.Categories[i].Name != "N/A")*@ // create new cat -> return 1 translation
                    {
                        <div class="form-group">
                            <label>
                                @Model.Categories[i].Name
                                <input type="checkbox" asp-for="Categories[i].Selected" />
                                <input type="hidden" asp-for="Categories[i].Id" />
                                <input type="hidden" asp-for="Categories[i].Name" />
                            </label>
                        </div>
                    }

                }
                <div class="form-group">
                    <input type="submit" value="Lưu lại" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Create.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductCreateRequest

@{
    ViewData["Title"] = "Tạo mới sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Tạo mới sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Create" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" required/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" type="number" class="form-control" required/>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="OriginalPrice" class="control-label"></label>
                        <input asp-for="OriginalPrice" type="number" class="form-control" required />
                        <span asp-validation-for="OriginalPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Stock" class="control-label"></label>
                        <input asp-for="Stock" type="number" class="form-control" required />
                        <span asp-validation-for="Stock" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea id="txt_details" asp-for="Details" rows="35" class="form-control"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoDescription" class="control-label"></label>
                        <input asp-for="SeoDescription" class="form-control" required />
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoTitle" class="control-label"></label>
                        <input asp-for="SeoTitle" class="form-control" required />
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoAlias" class="control-label"></label>
                        <input asp-for="SeoAlias" class="form-control" required />
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThumbnailImage" class="control-label"></label>
                        <input asp-for="ThumbnailImage" type="file" class="form-control" required />
                        <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="IsFeatured" class="control-label"></label>
                        <select asp-for="IsFeatured" class="form-control">
                            <option value="true">True</option>
                            <option value="false">False</option>
                        </select>
                        <span asp-validation-for="IsFeatured" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Tạo mới" class="btn btn-primary" required />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Delete.cshtml
@model eShopSolution.ViewModels.System.Products.ProductDeleteRequest

@{
    ViewData["Title"] = "Xóa sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Xóa sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Xóa sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Product">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Edit.cshtml
@model eShopSolution.ViewModels.Catalog.Products.ProductUpdateRequest

@{
    ViewData["Title"] = "Cập nhật sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_details'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Cập nhật sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật sản phẩm</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-8">
                <form asp-action="Edit" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea id="txt_details" asp-for="Details" rows="35" class="form-control"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoDescription" class="control-label"></label>
                        <input asp-for="SeoDescription" class="form-control" />
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoTitle" class="control-label"></label>
                        <input asp-for="SeoTitle" class="form-control" />
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoAlias" class="control-label"></label>
                        <input asp-for="SeoAlias" class="form-control" />
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThumbnailImage" class="control-label"></label>
                        <input asp-for="ThumbnailImage" type="file" class="form-control" />
                        <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
                    </div>
                       <div class="form-group">
                     <label asp-for="IsFeatured" class="control-label"></label>

                        <select asp-for="IsFeatured" class="form-control">
                            <option value="true">True</option>
                            <option value="false">False</option>
                        </select>
                        <span asp-validation-for="IsFeatured" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution.AdminApp/Views/Product/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.Catalog.Products.ProductVm>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Danh sách sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách sản phẩm</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Product">Tạo mới</a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-4">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                            </div>
                            <div class="col-md-4">
                                <select name="categoryId" onchange="this.form.submit()" asp-items="@ViewBag.Categories" class="form-control">
                                    <option>--Chọn danh mục--</option>
                                </select>
                            </div>
                            <div class="cold-md-3">
                                <button type="submit" class="btn btn-primary">Tìm</button>
                                <button type="button" onclick="window.location.href='/Product/Index'" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Mã SP
                            </th>
                            <th>
                                Tên
                            </th>
                            <th>
                                Giá nhập
                            </th>
                            <th>
                                Giá bán
                            </th>
                            <th>
                                Số lượng tồn
                            </th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.OriginalPrice)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Stock)
                                </td>
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                                 @*   @Html.ActionLink("Xem", "Details", new { id = item.Id }) |*@
                                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id }) |
                                    @Html.ActionLink("Gán danh mục", "CategoryAssign", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>